-- =============================================================================
-- Migration 016: ALLOC_TYPE (FRESH|GRT) markers for typed pool deduction
-- Spec: FSD_FRESH_GRT_HOLD_CONTROL.md FS-DB-02/03, FS-10.
--
--   ARS_PEND_ALC.ALLOC_TYPE          NVARCHAR(10) NULL  (NULL = legacy/manual → both pools)
--   ARS_ALLOC_HISTORY.ALLOC_TYPE     NVARCHAR(10) NULL
--   ARS_ALLOC_WORKING.ALLOC_TYPE     NVARCHAR(10) NULL  (stamped per run; promoted to history)
--   ARS_NL_TBL_HOLD_TRACKING         key widens to (WERKS, VAR_ART, SZ, ALLOC_TYPE)
--     ALLOC_TYPE NOT NULL DEFAULT '' — '' is the legacy/untyped sentinel because
--     PK columns cannot be NULL. Code treats '' and NULL as untyped.
--   ARS_NL_TBL_HOLD_TRACKING_SNAPSHOT — same widening (restore must keep type).
-- =============================================================================

-- 1) ARS_PEND_ALC ------------------------------------------------------------
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='ARS_PEND_ALC')
AND NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_NAME='ARS_PEND_ALC' AND COLUMN_NAME='ALLOC_TYPE')
BEGIN
    ALTER TABLE ARS_PEND_ALC ADD ALLOC_TYPE NVARCHAR(10) NULL;
    PRINT 'ARS_PEND_ALC.ALLOC_TYPE added.';
END
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='ARS_PEND_ALC' AND COLUMN_NAME='ALLOC_TYPE')
AND NOT EXISTS (SELECT 1 FROM sys.indexes
                WHERE name='IX_ARS_PEND_ALC_alloc_type' AND object_id=OBJECT_ID('ARS_PEND_ALC'))
BEGIN
    CREATE INDEX IX_ARS_PEND_ALC_alloc_type
        ON ARS_PEND_ALC (RDC, ARTICLE_NUMBER, ALLOC_TYPE)
        INCLUDE (ALLOC_QTY, DO_QTY, IS_CLOSED);
    PRINT 'IX_ARS_PEND_ALC_alloc_type created.';
END
GO

-- 2) ARS_ALLOC_HISTORY and ARS_ALLOC_WORKING ----------------------------------
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='ARS_ALLOC_HISTORY')
AND NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_NAME='ARS_ALLOC_HISTORY' AND COLUMN_NAME='ALLOC_TYPE')
BEGIN
    ALTER TABLE ARS_ALLOC_HISTORY ADD ALLOC_TYPE NVARCHAR(10) NULL;
    PRINT 'ARS_ALLOC_HISTORY.ALLOC_TYPE added.';
END
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='ARS_ALLOC_WORKING')
AND NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_NAME='ARS_ALLOC_WORKING' AND COLUMN_NAME='ALLOC_TYPE')
BEGIN
    ALTER TABLE ARS_ALLOC_WORKING ADD ALLOC_TYPE NVARCHAR(10) NULL;
    PRINT 'ARS_ALLOC_WORKING.ALLOC_TYPE added.';
END
GO

-- 3) ARS_NL_TBL_HOLD_TRACKING — add column, widen PK --------------------------
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='ARS_NL_TBL_HOLD_TRACKING')
AND NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_NAME='ARS_NL_TBL_HOLD_TRACKING' AND COLUMN_NAME='ALLOC_TYPE')
BEGIN
    ALTER TABLE ARS_NL_TBL_HOLD_TRACKING
        ADD ALLOC_TYPE NVARCHAR(10) NOT NULL
            CONSTRAINT DF_NL_TBL_HOLD_alloc_type DEFAULT '';
    PRINT 'ARS_NL_TBL_HOLD_TRACKING.ALLOC_TYPE added (default '''' = legacy).';
END
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='ARS_NL_TBL_HOLD_TRACKING' AND COLUMN_NAME='ALLOC_TYPE')
AND EXISTS (SELECT 1 FROM sys.key_constraints kc
            JOIN sys.index_columns ic ON ic.object_id=kc.parent_object_id
                 AND ic.index_id=kc.unique_index_id
            WHERE kc.name='PK_ARS_NL_TBL_HOLD_TRACKING'
            GROUP BY kc.name HAVING COUNT(*) = 3)   -- still the old 3-column PK
BEGIN
    ALTER TABLE ARS_NL_TBL_HOLD_TRACKING DROP CONSTRAINT PK_ARS_NL_TBL_HOLD_TRACKING;
    ALTER TABLE ARS_NL_TBL_HOLD_TRACKING
        ADD CONSTRAINT PK_ARS_NL_TBL_HOLD_TRACKING
        PRIMARY KEY CLUSTERED ([WERKS],[VAR_ART],[SZ],[ALLOC_TYPE]);
    PRINT 'PK_ARS_NL_TBL_HOLD_TRACKING widened to include ALLOC_TYPE.';
END
GO

-- 4) ARS_NL_TBL_HOLD_TRACKING_SNAPSHOT — same widening ------------------------
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='ARS_NL_TBL_HOLD_TRACKING_SNAPSHOT')
AND NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_NAME='ARS_NL_TBL_HOLD_TRACKING_SNAPSHOT' AND COLUMN_NAME='ALLOC_TYPE')
BEGIN
    ALTER TABLE ARS_NL_TBL_HOLD_TRACKING_SNAPSHOT
        ADD ALLOC_TYPE NVARCHAR(10) NOT NULL
            CONSTRAINT DF_NL_TBL_HOLD_SNAP_alloc_type DEFAULT '';
    DECLARE @pk sysname;
    SELECT @pk = kc.name FROM sys.key_constraints kc
    WHERE kc.parent_object_id = OBJECT_ID('ARS_NL_TBL_HOLD_TRACKING_SNAPSHOT')
      AND kc.type = 'PK';
    IF @pk IS NOT NULL
        EXEC('ALTER TABLE ARS_NL_TBL_HOLD_TRACKING_SNAPSHOT DROP CONSTRAINT [' + @pk + ']');
    ALTER TABLE ARS_NL_TBL_HOLD_TRACKING_SNAPSHOT
        ADD CONSTRAINT PK_ARS_NL_TBL_HOLD_TRACKING_SNAPSHOT
        PRIMARY KEY CLUSTERED ([SESSION_ID],[WERKS],[VAR_ART],[SZ],[ALLOC_TYPE]);
    PRINT 'Snapshot table widened to include ALLOC_TYPE.';
END
GO

PRINT 'Migration 016 complete.';
