CREATE OR ALTER PROC [dbo].[USP_PARK_TEMP]
(
 @SEG   VARCHAR(20) = '',  
 @DIV   VARCHAR(20) = ''  ,
 @SESSION VARCHAR(50) = NULL
)

AS
BEGIN
    
	IF @SESSION IS NULL
		BEGIN
			SELECT @SESSION = MAX([SESSION_ID]) FROM  ARS_ALLOC_HISTORY(NOLOCK)
		END
		

;    WITH MSA_QTY AS    
    (    
     SELECT
        a.RDC,a.MAJ_CAT,a.GEN_ART_NUMBER,a.CLR,
        SUM(a.FNL_Q) AS OP_MSA_QTY,SUM(a.FNL_Q) - COALESCE(MAX(b.consumed), 0) AS EXTRA_MSA_QTY,
        COALESCE(MAX(b.alloc_consumed), 0) AS ALC_Q,
        COALESCE(MAX(b.consumed), 0) AS ALC_HOLD_Q,
        COALESCE(MAX(b.HOLD_QTY), 0) AS HOLD_QTY,
        COUNT(*) AS BGT_SZ_COUNT,
        SUM(CASE WHEN a.FNL_Q > 0 THEN 1 ELSE 0 END) AS SZ_COUNT_WITH_MSA
        ,SUM(CASE WHEN (a.FNL_Q-b.consumed) > 0 THEN 1 ELSE 0 END) AS SZ_COUNT_AFTER_ALC

    FROM ARS_MSA_TOTAL_HISTORY a
    LEFT JOIN (SELECT RDC,MAJ_CAT,GEN_ART_NUMBER,CLR,SUM(hold_qty + ALLOC_QTY - FROM_HOLD_QTY) AS consumed,sum(alloc_qty) as alloc_consumed,SUM(HOLD_QTY) AS HOLD_QTY FROM ARS_LISTING_WORKING_HISTORY
    WHERE [SESSION_ID] = @SESSION GROUP BY RDC, MAJ_CAT, GEN_ART_NUMBER, CLR) b
        ON a.RDC = b.RDC AND a.MAJ_CAT = b.MAJ_CAT AND a.GEN_ART_NUMBER = b.GEN_ART_NUMBER AND A.CLR = b.CLR
    WHERE [SESSION_ID] = @SESSION
    GROUP BY A.RDC, A.MAJ_CAT, A.GEN_ART_NUMBER, A.CLR
    )

    , ALLOC_AGG AS    
    (    
     SELECT WERKS,MAJ_CAT,MERGE_RNG_SEG,RNG_SEG,M_YARN_02,FIT,GEN_ART_NUMBER,CLR,
        SUM(SUM(ALLOC_QTY)) OVER (PARTITION BY WERKS, MAJ_CAT,MERGE_RNG_SEG) AS MERGE_SEG_ALC,
        SUM(SUM(ALLOC_QTY)) OVER (PARTITION BY WERKS, MAJ_CAT) AS MAJ_CAT_ALC,
        SUM(SUM(ALLOC_QTY)) OVER (PARTITION BY WERKS, MAJ_CAT,RNG_SEG) AS RNG_SEG_ALC,
        SUM(SUM(ALLOC_QTY)) OVER (PARTITION BY WERKS, MAJ_CAT,M_YARN_02) AS MVGR1_ALC,
        SUM(SUM(ALLOC_QTY)) OVER (PARTITION BY WERKS, MAJ_CAT,FIT) AS FIT_ALC,
        SUM(SUM(ALLOC_QTY)) OVER (PARTITION BY RDC,MAJ_CAT,GEN_ART_NUMBER,CLR) AS ALC_TTL,
        SUM(SUM(HOLD_QTY)) OVER (PARTITION BY RDC,MAJ_CAT,GEN_ART_NUMBER,CLR) AS HOLD_TTL,
        SUM(SUM(FROM_HOLD_QTY)) OVER (PARTITION BY RDC,MAJ_CAT,GEN_ART_NUMBER,CLR) AS FROM_HOLD_TTL

    FROM ARS_LISTING_WORKING_HISTORY
    WHERE [SESSION_ID] = @SESSION
    GROUP BY WERKS,MAJ_CAT,MERGE_RNG_SEG,RNG_SEG,M_YARN_02,FIT,GEN_ART_NUMBER,CLR,RDC   
    ),        
    CTE_PRODUCT_MASTER    
    AS    
    (    
     SELECT GEN_ART_NUMBER, GEN_ART_DESC, SEG, DIV, SUB_DIV, MAJ_CAT, CLR,SSN,MRP    
     FROM VW_MASTER_PRODUCT    
     GROUP BY GEN_ART_NUMBER, GEN_ART_DESC, SEG, DIV, SUB_DIV, MAJ_CAT, CLR,SSN,MRP    
    )    
    ,BU_MBQ AS
    (
	    SELECT WERKS, MAJ_CAT, GEN_ART_NUMBER, CLR,
	    SUM(SZ_MBQ* case when alloc_round = 0 then 1 else alloc_round end) AS  SZ_MBQ_BU,
	    SUM(SZ_MBQ_WH* case when alloc_round = 0 then 1 else alloc_round end)-SUM(SZ_MBQ * case when alloc_round = 0 then 1 else alloc_round end) AS HOLD_MBQ_BU,
	    CASE WHEN ((sum(SZ_MBQ_WH * case when alloc_round = 0 then 1 else alloc_round end)-sum(SZ_STK)) -SUM(ALLOC_QTY)) <0 THEN 0 ELSE 
	    ((sum(SZ_MBQ_WH * case when alloc_round = 0 then 1 else alloc_round end)-sum(SZ_STK)) -SUM(ALLOC_QTY)) END as [VAR_SHORT_BU]
	    FROM ARS_ALLOC_HISTORY
	    WHERE FNL_Q_REM > 0 AND [SESSION_ID] = @SESSION
	    GROUP BY WERKS, MAJ_CAT, GEN_ART_NUMBER, CLR--,case when alloc_round = 0 then 1 else alloc_round end
    )
    , ALC_I_ROD_CNT AS
    (
	    SELECT  WERKS, MAJ_CAT, GEN_ART_NUMBER, CLR,
			    case when alloc_round = 0 then 1 else alloc_round end AS ALC_I_ROD
	    FROM ARS_ALLOC_HISTORY
        WHERE [SESSION_ID] = @SESSION
	    GROUP BY WERKS, MAJ_CAT, GEN_ART_NUMBER, CLR,case when alloc_round = 0 then 1 else alloc_round end 
    ),
    
    EXCESS_DATA AS
    (
    SELECT WERKS,MAJ_CAT,MERGE_RNG_SEG,RNG_SEG,M_YARN_02,FIT,GEN_ART_NUMBER,CLR,
        SUM(SUM(ART_EXCESS)) OVER (PARTITION BY WERKS, MAJ_CAT,MERGE_RNG_SEG) AS MERGE_SEG_EXCESS,
        SUM(SUM(ART_EXCESS)) OVER (PARTITION BY WERKS, MAJ_CAT) AS MAJ_CAT_EXCESS,
        SUM(SUM(ART_EXCESS)) OVER (PARTITION BY WERKS, MAJ_CAT,RNG_SEG) AS RNG_SEG_EXCESS,
        SUM(SUM(ART_EXCESS)) OVER (PARTITION BY WERKS, MAJ_CAT,M_YARN_02) AS MVGR1_EXCESS,
        SUM(SUM(ART_EXCESS)) OVER (PARTITION BY WERKS, MAJ_CAT,FIT) AS FIT_EXCESS
    FROM ARS_LISTING_HISTORY
    WHERE [SESSION_ID] = @SESSION
    GROUP BY WERKS,MAJ_CAT,MERGE_RNG_SEG,RNG_SEG,M_YARN_02,FIT,GEN_ART_NUMBER,CLR
    )
    select 
    A.[SESSION_ID],
     A.APPROVED_AT,
     A.WERKS AS ST_CD,    
     A.RDC,    
     L.SEG,    
     L.DIV,    
     L.SUB_DIV,    
     A.MAJ_CAT, 
     CASE WHEN j.SZ_APPLICABLE  = 'Y' THEN 1 ELSE 0 END SIZE_APPLICABLE,
     ACS_D AS ACC_DENSISTY,
     ALC_D AS ALC_DAYS,
     L.SSN,    
     A.GEN_ART_NUMBER AS [GEN-ART],    
     A.GEN_ART_DESC AS [GEN-ART-DESC],    
     A.CLR,    
     F.MRP,    
     A.RNG_SEG,    
     A.MERGE_RNG_SEG AS M_RNG_SEG,    
     A.M_YARN_02 [FAB_MAIN_MVGR-1],    
     A.WEAVE_2 [FAB_MAIN_MVGR-2],
     A.FAB,
     A.FIT AS FIT,
     CONCAT(
           CASE WHEN GH_MJ = 1 THEN 'MJ'  END,
           CASE WHEN GH_MERGE_RNG_SEG = 1 THEN '|MERGE_RNG_SEG'  END,
           CASE WHEN GH_RNG_SEG = 1 THEN '|RNG_SEG'  END,
           CASE WHEN GH_M_YARN_02 = 1 THEN '|M_YARN_02'  END,
           CASE WHEN GH_WEAVE_2 = 1 THEN '|WEAVE_2'  END,
           CASE WHEN GH_FAB = 1 THEN '|FAB' END,
           CASE WHEN GH_CLR = 1 THEN '|CLR'  END,
           CASE WHEN GH_M_VND_CD = 1 THEN '|M_VND_CD'  END,
           CASE WHEN GH_FIT = 1 THEN '|FIT'  END
       ) AS ALC_GRID,
     OPT_TYPE AS ART_TYPE,

     OPT_STATUS AS ART_TYPE_FINAL,
     --CASE    
     -- WHEN OPT_TYPE = 'TBL' AND ALLOC_QTY > 0 AND 1.0*(STK_TTL + ALLOC_QTY)/NULLIF(OPT_MBQ,0) >= 0.6 THEN 'NL'    
     -- WHEN OPT_TYPE = 'TBL' AND ALLOC_QTY > 0 AND 1.0*(STK_TTL + ALLOC_QTY)/NULLIF(OPT_MBQ,0) <  0.6 THEN 'MIX'    
     -- WHEN OPT_TYPE = 'RL'  AND ALLOC_QTY > 0 THEN 'RL'    
     -- WHEN OPT_TYPE = 'RL'  AND ALLOC_QTY = 0 AND C.OP_MSA_QTY > 50 THEN 'WRL'    
     -- WHEN OPT_TYPE = 'TBC' AND ALLOC_QTY > 0 AND 1.0*(STK_TTL + ALLOC_QTY)/NULLIF(OPT_MBQ,0) >= 0.6 THEN 'RL'    
     -- WHEN OPT_TYPE = 'TBC' THEN 'MIX'    
     -- WHEN 1.0*STK_TTL/NULLIF(OPT_MBQ,0) >= 0.6 AND ALLOC_QTY = 0 AND C.OP_MSA_QTY = 0 THEN 'L'    
     -- ELSE 'NA'    
     --END AS ART_TYPE_FINAL,    
     ISNULL(AGE,0) AS [FIRST AGING],  
 
     I_ROD AS [MAX-I-ROD],
     ISNULL(K.ALC_I_ROD,0) AS [ALC-I-ROD],
     OPT_MBQ * case when ISNULL(K.ALC_I_ROD,0)=0 then 1 else ISNULL(K.ALC_I_ROD,0) end as OPT_MBQ,    
     OPT_MBQ_WH * case when ISNULL(K.ALC_I_ROD,0)=0 then 1 else ISNULL(K.ALC_I_ROD,0) end as OPT_MBQ_WH,    
     STK_TTL AS [BEFORE ST_TTL],    
     STK_TTL + ALLOC_QTY AS [AFTER_STK_TTL_Q], 
     ISNULL([VAR_SHORT_BU],0) AS [VAR_SHORT_BU],
     MAX_DAILY_SALE AS [PD_SALE],    
     GREATEST((OPT_MBQ * case when ISNULL(K.ALC_I_ROD,0)=0 then 1 else ISNULL(K.ALC_I_ROD,0) end)-STK_TTL,0) AS OPT_REQ,    
     GREATEST((OPT_MBQ_WH * case when ISNULL(K.ALC_I_ROD,0)=0 then 1 else ISNULL(K.ALC_I_ROD,0) end)-STK_TTL,0) as OPT_REQ_WH,    
     ALLOC_QTY AS [ALLOC_Q_MACHINE],    
     ROUND(STK_TTL/NULLIF(OPT_MBQ,0),2) AS BEFORE_FILL_RATE_PCT,    
     ROUND((STK_TTL + ALLOC_QTY)/NULLIF(OPT_MBQ,0),2)  AS AFTER_FILL_RATE_PCT,    
     A.HOLD_QTY,
     D.ALC_TTL AS [ALC_TTL],
     D.HOLD_TTL AS [HOLD_TTL],
     ISNULL(A.RL_HOLD_QTY,0) AS [HOLD_Q_INIT],
     GREATEST((ISNULL(A.RL_HOLD_QTY,0)+ISNULL(A.HOLD_QTY,0))-ISNULL(A.FROM_HOLD_QTY,0),0) AS [HOLD_Q_CLS],
     ISNULL(A.FROM_HOLD_QTY,0) AS [FROM_HOLD_QTY],
     ISNULL(D.FROM_HOLD_TTL,0) FROM_HOLD_TTL,
     C.EXTRA_MSA_QTY EXTRA_MSA_QTY,    
     C.OP_MSA_QTY,    
     C.BGT_SZ_COUNT,    
     C.SZ_COUNT_WITH_MSA,
     SZ_COUNT_AFTER_ALC,

        --MAJ_CAT WISE
     A.MJ_DISP_Q AS BGT_DISP_Q,    
     A.MJ_MBQ AS BGT_MBQ,
     MAJ_CAT_EXCESS AS MAJ_CAT_EXCESS,
     A.MJ_STK_TTL AS BEFORE_ALC_ST_TTL_STK_Q    
     ,D.MAJ_CAT_ALC+ A.MJ_STK_TTL AS AFTER_ALC_ST_TTL_STK_Q    
     ,A.MJ_REQ AS [ST_MJ_REQ]    
     , D.MAJ_CAT_ALC AS ALC_QTY 
     ,CASE WHEN (A.MJ_REQ-D.MAJ_CAT_ALC)<0 THEN 0 ELSE (A.MJ_REQ-D.MAJ_CAT_ALC) END  AS REQ_REM_Q
     --, CASE WHEN MJ_MBQ - (D.MAJ_CAT_ALC+ A.MJ_STK_TTL) < 0 THEN 0 ELSE MJ_MBQ - (D.MAJ_CAT_ALC+ A.MJ_STK_TTL) END AS REQ_REM_Q    
     ,MJ_CONT AS BGT_OPT_CNT  
     
        --MERGE_SEG_WISE
     ,A.MERGE_RNG_SEG_DISP_Q AS BGT_MERGE_RNG_SEG_DISP_Q    
     ,A.MERGE_RNG_SEG_MBQ AS BGT_MERGE_RNG_SEG_MBQ
     ,MERGE_SEG_EXCESS AS MERGE_SEG_EXCESS
     ,A.MERGE_RNG_SEG_STK_TTL AS BEFORE_ALC_MERGE_RNG_SEG_STK_Q    
     ,MERGE_SEG_ALC+ A.MERGE_RNG_SEG_STK_TTL AS AFTER_ALC_MERGE_RNG_SEG_STK_Q    
     ,A.MERGE_RNG_SEG_REQ AS [ST_MERGE_RNG_SEG_REQ]    
     ,MERGE_SEG_ALC AS ALC_MERGE_RNG_SEG_QTY    
     ,CASE WHEN MERGE_RNG_SEG_MBQ - (MERGE_SEG_ALC+ A.MERGE_RNG_SEG_STK_TTL) < 0 THEN 0 ELSE MERGE_RNG_SEG_MBQ - (MERGE_SEG_ALC+ A.MERGE_RNG_SEG_STK_TTL) END AS ST_MERGE_RNG_SEG_REQ_REM_Q    
     ,MERGE_RNG_SEG_OPT_CNT AS MERGE_RNG_SEG_BGT_OPT_CNT
     --RNG_SEG_WISE
     ,A.RNG_SEG_DISP_Q AS BGT_RNG_SEG_DISP_Q
     ,A.RNG_SEG_MBQ AS BGT_RNG_SEG_MBQ
     ,RNG_SEG_EXCESS AS RNG_SEG_EXCESS
     ,A.RNG_SEG_STK_TTL AS BEFORE_ALC_RNG_SEG_STK_TTL    
     ,RNG_SEG_ALC+ A.RNG_SEG_STK_TTL AS AFTER_ALC_RNG_SEG_STK_Q    
     ,A.RNG_SEG_REQ AS [ST_RNG_SEG_REQ]    
     ,RNG_SEG_ALC AS ALC_RNG_SEG_QTY    
     ,CASE WHEN RNG_SEG_MBQ - (RNG_SEG_ALC+ A.RNG_SEG_STK_TTL) < 0 THEN 0 ELSE RNG_SEG_MBQ - (RNG_SEG_ALC+ A.RNG_SEG_STK_TTL) END AS ST_RNG_SEG_REQ_REM_Q    
     ,RNG_SEG_OPT_CNT AS RNG_SEG_BGT_OPT_CNT

     --M_YARN_02 (MVGR-1) WISE
     ,A.M_YARN_02_DISP_Q AS BGT_FAB_MVGR_1_DISP_Q
     ,A.M_YARN_02_MBQ AS BGT_FAB_MVGR_1_MBQ 
     ,MVGR1_EXCESS AS FAB_MVGR_1_EXCESS
     ,A.M_YARN_02_STK_TTL AS BEFORE_ALC_FAB_MVGR_1_STK_TTL    
     ,MVGR1_ALC+ A.M_YARN_02_STK_TTL AS AFTER_ALC_MVGR_1_STK_Q    
     ,A.M_YARN_02_REQ AS [ST_MVGR_1_REQ]    
     ,MVGR1_ALC AS ALC_MVGR_1_QTY    
     ,CASE WHEN M_YARN_02_MBQ - (MVGR1_ALC+ A.M_YARN_02_STK_TTL) < 0 THEN 0 ELSE M_YARN_02_MBQ - (MVGR1_ALC+ A.M_YARN_02_STK_TTL) END AS ST_MVGR_1_REQ_REM_Q    
     ,M_YARN_02_OPT_CNT AS MVGR_1_BGT_OPT_CNT

     --FIT WISE
     ,A.[FIT_DISP_Q] AS BGT_FIT_DISP_Q
     ,A.FIT_MBQ AS BGT_FIT_MBQ 
     ,FIT_EXCESS AS FIT_EXCESS
     ,A.FIT_STK_TTL AS BEFORE_ALC_FIT_STK_TTL    
     ,FIT_ALC+ A.FIT_STK_TTL AS AFTER_ALC_FIT_STK_Q    
     ,A.FIT_REQ AS [ST_FIT_REQ]    
     ,FIT_ALC AS ALC_FIT_QTY    
     ,CASE WHEN FIT_MBQ - (FIT_ALC+ A.FIT_STK_TTL) < 0 THEN 0 ELSE FIT_MBQ - (FIT_ALC+ A.FIT_STK_TTL) END AS ST_FIT_REQ_REM_Q    
     ,FIT_OPT_CNT AS FIT_BGT_OPT_CNT

     , ISNULL(G.HOLD_MBQ_BU,0) AS HOLD_MBQ_BU
     , ISNULL(G.SZ_MBQ_BU,0) AS SZ_MBQ_BU
     ,LISTED_REASON
     ,ALLOC_REASON
     ,ALLOC_REMARKS

     --,ISNULL(MAJ_CAT_EXCESS,0) AS ST_MAJ_CAT_EXCESS
      --,ISNULL(MERGE_SEG_EXCESS,0) AS ST_MAJ_CAT_M_RNG_SEG_EXCESS
      


    from     
     ARS_LISTING_WORKING_HISTORY A    
    LEFT JOIN MSA_QTY  C ON A.RDC=C.RDC AND A.MAJ_CAT=C.MAJ_CAT AND A.GEN_ART_NUMBER=C.GEN_ART_NUMBER AND A.CLR=C.CLR    
    LEFT JOIN ALLOC_AGG  D ON A.WERKS = D.WERKS AND A.MAJ_CAT = D.MAJ_CAT AND A.GEN_ART_NUMBER = D.GEN_ART_NUMBER AND A.CLR = D.CLR    
    LEFT JOIN CTE_PRODUCT_MASTER F ON A.GEN_ART_NUMBER = F.GEN_ART_NUMBER AND A.CLR = F.CLR AND A.MAJ_CAT = F.MAJ_CAT 
    LEFT JOIN BU_MBQ G ON A.WERKS = G.WERKS AND A.MAJ_CAT = G.MAJ_CAT AND A.GEN_ART_NUMBER = G.GEN_ART_NUMBER AND A.CLR = G.CLR
    LEFT JOIN ALC_I_ROD_CNT K ON A.WERKS = K.WERKS AND A.MAJ_CAT =K.MAJ_CAT AND A.GEN_ART_NUMBER = K.GEN_ART_NUMBER AND A.CLR = K.CLR
    LEFT JOIN EXCESS_DATA H ON A.WERKS = H.WERKS AND A.MAJ_CAT =H.MAJ_CAT AND A.GEN_ART_NUMBER = H.GEN_ART_NUMBER AND A.CLR = H.CLR
    --left join alc_from_hold I ON A.WERKS = I.WERKS AND A.MAJ_CAT =I.MAJ_CAT AND A.GEN_ART_NUMBER = I.GEN_ART_NUMBER AND A.CLR = I.CLR
    LEFT JOIN ARS_GRID_HIERARCHY (NOLOCK) J ON A.MAJ_CAT = J.MAJ_CAT
    LEFT JOIN (SELECT DISTINCT MAJ_CAT,SEG,DIV,SUB_DIV,SSN FROM VW_MASTER_PRODUCT) L ON A.MAJ_CAT = L.MAJ_CAT

    	
		WHERE SESSION_ID = @SESSION

	 AND
	 (@SEG = '' OR @SEG IS NULL OR f.SEG = @SEG)  
	   AND (@DIV = '' OR @DIV IS NULL OR f.DIV = @DIV)

	   OPTION(RECOMPILE)
	--and a.GEN_ART_NUMBER='1110114523'--and A.WERKS='HI06' --AND /*A.MAJ_CAT='M_W_PYJAMA'*/ A.GEN_ART_NUMBER='1114093375' AND A.CLR='M_GRY'
    --and A.GEN_ART_NUMBER=1114093375 --and A.clr ='cof'
 

 END


 --USP_PARK_TEMP